import nodemailer from 'nodemailer';
import { supabaseAdmin } from '@/backend/lib/supabase/admin';

/**
 * Monthly electricity report mailer (Phase 5 of docs/ELECTRICITY_AUTOMATION_PLAN.md).
 *
 * Transport config mirrors backend/lib/council/mailer.ts (same env vars, same defaults).
 * EmailService.sendEmail is not used because it exposes no attachments param at the time
 * of writing; if one lands later this file can be swapped to it without touching callers.
 *
 * Every send is wrapped: callers get `{ sent: false, error }` instead of a throw, so a
 * broken SMTP session fails that org's report cleanly in the cron summary rather than
 * aborting the whole run.
 */

const smtpUser = process.env.SMTP_USER || process.env.EMAIL_SMTP_USER;
const smtpPass = process.env.SMTP_PASS || process.env.EMAIL_SMTP_PASS;
const smtpHost = process.env.SMTP_HOST || process.env.EMAIL_SMTP_HOST || 'smtp.gmail.com';
const smtpPort = parseInt(process.env.SMTP_PORT || process.env.EMAIL_SMTP_PORT || '465');

const transporter = nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: process.env.SMTP_SECURE === 'true' || smtpPort === 465,
    auth: {
        user: smtpUser,
        pass: smtpPass,
    },
});

export interface ReportSendResult {
    sent: boolean;
    error?: string;
}

/**
 * Who receives the monthly pack: active members of the org holding the checker role
 * (ops_super_admin) plus the org super admins. Master admins are platform-side, not
 * org-side, and are deliberately not emailed.
 */
export async function loadReportRecipients(organizationId: string): Promise<string[]> {
    const { data: memberships } = await supabaseAdmin
        .from('organization_memberships')
        .select('user_id')
        .eq('organization_id', organizationId)
        .eq('is_active', true)
        .in('role', ['ops_super_admin', 'org_super_admin']);

    const userIds = [...new Set((memberships || []).map(m => m.user_id).filter(Boolean))];
    if (!userIds.length) return [];

    const { data: users } = await supabaseAdmin
        .from('users').select('email').in('id', userIds);

    return [...new Set(
        (users || []).map(u => u.email).filter((e): e is string => !!e),
    )];
}

export async function sendMonthlyReport({
    to,
    orgName,
    monthLabel,
    pdf,
    filename,
}: {
    to: string[];
    orgName: string;
    /** Human label, e.g. "July 2026". */
    monthLabel: string;
    pdf: Buffer;
    filename: string;
}): Promise<ReportSendResult> {
    if (!smtpUser) {
        return { sent: false, error: 'SMTP credentials not configured' };
    }
    if (!to.length) {
        return { sent: false, error: 'No ops_super_admin / org_super_admin recipients' };
    }
    try {
        await transporter.sendMail({
            from: `"Autopilot FMS" <${process.env.SMTP_SENDER_EMAIL || smtpUser}>`,
            to: to.join(', '),
            subject: `Electricity monthly report — ${monthLabel} — ${orgName}`,
            html:
                `<p>The electricity monthly report for <strong>${monthLabel}</strong> is attached.</p>`
                + `<p>It covers the bill register, validation results and variances, open disputes,`
                + ` early-payment discount performance, and chase/reliability activity for ${orgName}.</p>`
                + `<p style="color:#6B7280;font-size:12px">Generated by Autopilot FMS — not hand-written.</p>`,
            attachments: [{ filename, content: pdf, contentType: 'application/pdf' }],
        });
        return { sent: true };
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        console.error('[ElectricityReportMailer] send failed:', message);
        return { sent: false, error: message };
    }
}
