-- ============================================================================
-- CONNECTED MAILBOXES — one OAuth app, many people, no code change per agent.
-- ----------------------------------------------------------------------------
-- Until now a mailbox was a set of environment variables. Adding one meant a
-- Zoho Self Client generated by hand, three secrets pasted into .env, and a
-- deploy. That does not scale past the first agent: every future agent is
-- linked to a different person's inbox, and nobody is going to mint a client id
-- and secret each time.
--
-- The fix is the ordinary OAuth shape. ONE server-based application, created
-- once. Each person then clicks "Connect my mailbox" in the console, consents
-- as themselves, and Zoho hands back a refresh token for THEIR account. This
-- table is where those land.
--
-- A Zoho grant reaches exactly one account's mailboxes, which is a feature:
-- purchase@ cannot read anybody's private inbox, and an agent reading replies
-- in someone's personal mail has only the access that person granted, revocable
-- by them at any time.
--
-- ── ON STORING THE REFRESH TOKEN ────────────────────────────────────────────
-- oem_agent_credentials deliberately refuses to hold pasted secrets, because a
-- secret with no consumer is a stored liability plus a false assurance. That
-- reasoning does not apply here: this token HAS a consumer (the mail poller),
-- it cannot be an env var because it is minted per person at runtime, and the
-- whole point is that an operator adds one without a deploy.
--
-- It is encrypted application-side (AES-256-GCM, key in MAIL_TOKEN_KEY) before
-- it is written, so the database never holds a usable token and a backup or a
-- replica leaks nothing. The column is never returned to a client — the API
-- exposes the address, the aliases and the health, and nothing else.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.oem_mail_accounts (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,

    -- The account's primary address, e.g. lohitaksha.ranganathan@worksquare.in
    address          text NOT NULL,
    -- Every address this grant can read, primaries and aliases. This is what an
    -- agent's poll list is matched against, so an alias works with no extra setup.
    addresses        text[] NOT NULL DEFAULT '{}',
    zoho_account_id  text,

    -- AES-256-GCM, base64. NEVER returned to a client, never logged.
    refresh_token_enc text NOT NULL,
    -- Which data centre minted it. A refresh token is DC-locked.
    dc               text NOT NULL DEFAULT 'com',
    scopes           text,

    connected_by     uuid REFERENCES public.users(id),
    connected_at     timestamptz NOT NULL DEFAULT now(),
    -- Health, so a revoked grant is visible in the console instead of surfacing
    -- as an agent that has mysteriously gone quiet.
    last_ok_at       timestamptz,
    last_error       text,
    is_active        boolean NOT NULL DEFAULT true,

    UNIQUE (organization_id, address)
);

CREATE INDEX IF NOT EXISTS idx_mail_accounts_org
    ON public.oem_mail_accounts(organization_id) WHERE is_active;
CREATE INDEX IF NOT EXISTS idx_mail_accounts_addresses
    ON public.oem_mail_accounts USING GIN (addresses);

COMMENT ON TABLE public.oem_mail_accounts IS
    'SECRETS. RLS on with no permissive policy: only the service role reads it. refresh_token_enc must never reach a client or a log.';
COMMENT ON COLUMN public.oem_mail_accounts.addresses IS
    'Every address reachable on this grant, including aliases. An agent poll address is matched against this, so pointing an agent at an alias needs no further setup.';

ALTER TABLE public.oem_mail_accounts ENABLE ROW LEVEL SECURITY;
-- Deliberately NO permissive policy. Service role only.

-- The short-lived state for an in-flight consent. Rows are single-use and
-- expire; without this, a callback could be replayed or pointed at another org.
CREATE TABLE IF NOT EXISTS public.oem_mail_oauth_state (
    state            text PRIMARY KEY,
    organization_id  uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    created_by       uuid REFERENCES public.users(id),
    redirect_to      text,
    created_at       timestamptz NOT NULL DEFAULT now(),
    consumed_at      timestamptz
);

ALTER TABLE public.oem_mail_oauth_state ENABLE ROW LEVEL SECURITY;
